name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
#  get-changed-files:
#    name: Get changed files
#    runs-on: ubuntu-latest
#    outputs:
#      matrix: ${{ steps.changed-files.outputs.all_modified_files }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v6
#
#      - name: Get changed files
#        id: changed-files
#        uses: tj-actions/changed-files@v47
#        with:
#          matrix: true
#          files: |
#            modules/**
#            ./*.tf
#            ./*.tfvars

  test:
    name: Test
#    needs: get-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.matrix != '[]' }}
    steps:
      - name: Repo checkout
        uses: actions/checkout@v6

      - name: Prepare OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          cache: true

      - name: OT fmt
        run: tofu fmt -check

      - name: OT Init
        run: tofu init

      - name: OT Validate
        run: tofu validate -no-color

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.PROD_AWS_REGION }}
          role-to-assume: ${{ vars.PROD_AWS_ROLE_ARN }}
          mask-aws-account-id: true
          retry-max-attempts: 5

      - name: OT Plan
        run: tofu plan -no-color

  results:
    name: Test results
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    steps:
      - run: |
          result="${{ needs.test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
