name: Validation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          files: |
            modules/**
            ./*.tf
            ./*.tfvars

  validate:
    name: Validation
    needs: get-changed-files
    runs-on: ubuntu-latest
    environment:
      name: staging
    if: ${{ needs.get-changed-files.outputs.matrix != '[]' }}
    steps:
      - name: Repo checkout
        uses: actions/checkout@v6

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: '1'

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Validate Python files compilable
        run: python -m compileall modules/lambda

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check --config ruff.toml --output-format=github

      - name: Prepare OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          cache: true

      - name: OT Init
        run: tofu init -backend-config="key=staging/terraform.tfstate"

      - name: OT fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OT Validate
        run: tofu validate -no-color

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          mask-aws-account-id: true
          retry-max-attempts: 5

      - name: OT Plan
        run: tofu plan -no-color -var-file="staging.tfvars"

  results:
    name: Validation results
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    steps:
      - run: |
          result="${{ needs.validate.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
